#include "헤더들.h";

void mergeal() {
    int p=0;
    int list[9];
    char text[100];
    
    initArray(list, 8);
    ScreenRelease();
    system("cls");
    gotoxy(200, 20);
    printf("합병정렬\n배열을 원자값이 될 때까지 반으로 나누고, 배열을 합병하며 정렬하여 전체 리스트를 정렬하는 방식이다. \n");
    gotoxy(200, 5);
    printf("요소를 입력해주세요. 0을 입력하면 모든 값 랜덤. (나가려면 esc를 누르고 요소를 하나 더 입력해주세요)\n");
    for (int i = 0; i < 8; i++) {
        gotoxy(200, 6 + i);
        printf("%d번째 요소: ", i);
        scanf_s("%d", &list[i]);
        if ((GetAsyncKeyState(VK_ESCAPE) & 1) != 0) {
            ScreenInit();
            return;
        }
        if (list[i] == 0) {
            initArray(list, 8);
            break;
        }
    }
    ScreenInit();
    ScreenClear();
    printsq(40,0);
    printsq(50, 0);
    printsq(60, 0);
    printsq(70, 0);
    printsq(80, 0);
    printsq(90, 0);
    printsq(100, 0);
    printsq(110, 0);
    sprintf(text, "%d",list[0]);
    ScreenPrint(45, 2, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55, 2, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65, 2, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75, 2, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85, 2, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95, 2, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105, 2, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115, 2, text);
    ScreenFlipping();
    Sleep(1000);
    ScreenClear();

    printsq(40-1, 1);
    printsq(50-1, 1);
    printsq(60-1, 1);
    printsq(70-1, 1);
    printsq(80+1, 1);
    printsq(90+1, 1);
    printsq(100+1,1);
    printsq(110+1,1);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45-1, 3, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55-1, 3, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65-1, 3, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75-1, 3, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85+1, 3, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95+1, 3, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105+1,3, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115+1,3, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();

    printsq(40-2, 2);
    printsq(50-2, 2);
    printsq(60-2, 2);
    printsq(70-2, 2);
    printsq(80+2, 2);
    printsq(90+2, 2);
    printsq(100+2,2);
    printsq(110+2,2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45-2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55-2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65-2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75-2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85+2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95+2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105+2,4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115+2,4, text);
    ScreenFlipping();
    Sleep(500);
    ScreenClear();


    printsq(40-3, 3);
    printsq(50-3, 3);
    printsq(60-3, 3);
    printsq(70-3, 3);
    printsq(80+2, 2);
    printsq(90+2, 2);
    printsq(100+2,2);
    printsq(110+2,2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45-3, 5, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55-3, 5, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65-2, 5, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75-2, 5, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85+2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95+2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105+2,4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115+2,4, text);
    ScreenFlipping();
    Sleep(500);



    ScreenClear();
    printsq(40 - 4, 4);
    printsq(50 - 4, 4);
    printsq(60 - 2, 4);
    printsq(70 - 2, 4);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2,2);
    printsq(110 + 2,2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 4, 6, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 4, 6, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 6, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 6, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2,4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2,4, text);
    ScreenFlipping();
    Sleep(500);


    ScreenClear();
    printsq(40 - 5, 5);
    printsq(50 - 4, 5);
    printsq(60 - 2, 4);
    printsq(70 - 2, 4);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2,2);
    printsq(110 + 2,2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 5, 7, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 4, 7, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 6, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 6, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2,4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2,4, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();
    printsq(40 - 6, 6);
    printsq(50 - 4, 6);
    printsq(60 - 2, 4);
    printsq(70 - 2, 4);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 6, 8, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 4, 8, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 6, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 6, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);
    if (list[0] > list[1]) {
        int temp = list[0];
        list[0] = list[1];
        list[1] = temp;
    }
    ScreenClear();
    printsq(40 - 5, 5);
    printsq(50 - 4, 5);
    printsq(60 - 2, 4);
    printsq(70 - 2, 4);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 5, 7, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 4, 7, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 6, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 6, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();
    printsq(40 - 4, 4);
    printsq(50 - 4, 4);
    printsq(60 - 2, 4);
    printsq(70 - 2, 4);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 4, 6, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 4, 6, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 6, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 6, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);

    ////////////////////////////////////////////

    ScreenClear();
    printsq(40 - 5, 4);
    printsq(50 - 5, 4);
    printsq(60 - 3, 5);
    printsq(70 - 2, 5);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 5, 6, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 5, 6, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 3, 7, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 7, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();
    printsq(40 - 6, 4);
    printsq(50 - 6, 4);
    printsq(60 - 4, 6);
    printsq(70 - 2, 6);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 6, 6, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 6, 6, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 4, 8, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 8, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);
    if (list[2] > list[3]) {
        int temp = list[2];
        list[2] = list[3];
        list[3] = temp;
    }
    ScreenClear();
    printsq(40 - 5, 4);
    printsq(50 - 5, 4);
    printsq(60 - 3, 5);
    printsq(70 - 2, 5);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 5, 6, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 5, 6, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 3, 7, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 7, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();
    printsq(40 - 4, 4);
    printsq(50 - 4, 4);
    printsq(60 - 2, 4);
    printsq(70 - 2, 4);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 4, 6, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 4, 6, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 6, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 6, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);
    int list2[9];
    int temp;
    for (int o = 0; o < 4; o++) {
        for (int i = 0; i < 4; i++) {
            if (list[o] < list[i]) {
                temp = list[o];
                list[o] = list[i];
                list[i] = temp;
            }
        }
    }
     
    
    ScreenClear();
    printsq(40 - 3, 3);
    printsq(50 - 3, 3);
    printsq(60 - 2, 3);
    printsq(70 - 2, 3);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 3, 5, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 3, 5, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 5, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 5, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);
    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 3);
    printsq(90 + 2, 3);
    printsq(100 + 3, 3);
    printsq(110 + 3, 3);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 5, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 5, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 3,5, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 3,5, text);
    ScreenFlipping();
    Sleep(500);



    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 4);
    printsq(90 + 2, 4);
    printsq(100 + 4, 4);
    printsq(110 + 4, 4);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 6, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 6, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 4,6, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 4,6, text);
    ScreenFlipping();
    Sleep(500);


    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 5);
    printsq(90 + 3, 5);
    printsq(100 + 5,4);
    printsq(110 + 5,4);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 7, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 3, 7, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 5, 6, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 5, 6, text);
    ScreenFlipping();
    Sleep(500);
    
    ///////////////////////////kinhiugbiugik
    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 6);
    printsq(90 + 4, 6);
    printsq(100 + 6, 4);
    printsq(110 + 6, 4);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 8, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 4, 8, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 6,6, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 6,6, text);
    ScreenFlipping();
    Sleep(500);
    if (list[4] > list[5]) {
        int temp = list[4];
        list[4] = list[5];
        list[5] = temp;
    }
    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 5);
    printsq(90 + 3, 5);
    printsq(100 + 5,4);
    printsq(110 + 5,4);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 7, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 3, 7, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 5,6,text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 5,6, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 4);
    printsq(90 + 2, 4);
    printsq(100 + 4, 4);
    printsq(110 + 4, 4);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 6, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 6, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 4, 6, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 4, 6, text);
    ScreenFlipping();
    Sleep(500);

    ////////////////////////////////////////////

    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 4);
    printsq(90 + 2, 4);
    printsq(100 + 4, 5);
    printsq(110 + 5, 5);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 6, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 6, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 4, 7, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 5, 7, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 4);
    printsq(90 + 2, 4);
    printsq(100 + 4, 6);
    printsq(110 + 6, 6);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 6, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 6, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 4, 8, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 6, 8, text);
    ScreenFlipping();
    Sleep(500);
    if (list[6] > list[7]) {
        int temp = list[6];
        list[6] = list[7];
        list[7] = temp;
    }
    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 4);
    printsq(90 + 2, 4);
    printsq(100 + 4, 5);
    printsq(110 + 5, 5);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 6, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 6, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 4, 7, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 5, 7, text);
    ScreenFlipping();
    Sleep(500);
    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 4);
    printsq(90 + 2, 4);
    printsq(100 + 4,4);
    printsq(110 + 4,4);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 6, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 6, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 4, 6, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 4, 6, text);
    ScreenFlipping();
    Sleep(500);
    temp=0;
    for (int o = 4; o < 8; o++) {
        for (int i = 4; i < 8; i++) {
            if (list[o] < list[i]) {
                temp = list[o];
                list[o] = list[i];
                list[i] = temp;
            }
        }
    }
    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 3);
    printsq(90 + 2, 3);
    printsq(100 + 3,3);
    printsq(110 + 3,3);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 5, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 5, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 3, 5, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 3, 5, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();
    printsq(40 - 2, 2);
    printsq(50 - 2, 2);
    printsq(60 - 2, 2);
    printsq(70 - 2, 2);
    printsq(80 + 2, 2);
    printsq(90 + 2, 2);
    printsq(100 + 2, 2);
    printsq(110 + 2, 2);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 2, 4, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 2, 4, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 2, 4, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 2, 4, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 2, 4, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 2, 4, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 2, 4, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 2, 4, text);
    ScreenFlipping();
    Sleep(500);
    temp = 0;
    for (int o = 0; o < 8; o++) {
        for (int i = 0; i < 8; i++) {
            if (list[o] < list[i]) {
                temp = list[o];
                list[o] = list[i];
                list[i] = temp;
            }
        }
    }
    ScreenClear();
    printsq(40 - 1, 1);
    printsq(50 - 1, 1);
    printsq(60 - 1, 1);
    printsq(70 - 1, 1);
    printsq(80 + 1, 1);
    printsq(90 + 1, 1);
    printsq(100 + 1, 1);
    printsq(110 + 1, 1);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 - 1, 3, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 - 1, 3, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 - 1, 3, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 - 1, 3, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 + 1, 3, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95 + 1, 3, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105 + 1,3, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115 + 1, 3, text);
    ScreenFlipping();
    Sleep(500);

    ScreenClear();
    printsq(40 , 0);
    printsq(50 , 0);
    printsq(60 , 0);
    printsq(70 , 0);
    printsq(80 , 0);
    printsq(90 , 0);
    printsq(100, 0);
    printsq(110, 0);
    sprintf(text, "%d", list[0]);
    ScreenPrint(45 , 2, text);
    sprintf(text, "%d", list[1]);
    ScreenPrint(55 , 2, text);
    sprintf(text, "%d", list[2]);
    ScreenPrint(65 , 2, text);
    sprintf(text, "%d", list[3]);
    ScreenPrint(75 , 2, text);
    sprintf(text, "%d", list[4]);
    ScreenPrint(85 , 2, text);
    sprintf(text, "%d", list[5]);
    ScreenPrint(95, 2, text);
    sprintf(text, "%d", list[6]);
    ScreenPrint(105, 2, text);
    sprintf(text, "%d", list[7]);
    ScreenPrint(115, 2, text);
    ScreenFlipping();
    Sleep(500);

    _getch();
}
void printsq(int x,int y) {
    char sq[50][50] = {
        " ---------",
        "|         |",
        "|         |",
        " ---------"
    };
    char text[50];
    for (int i = 0; i < 14; i++) {
        sprintf(text, sq[i]);
        ScreenPrint(x, i+y, text);
    }
}
void printNode(node* ary) {

}